config/routes.rb
PofPm::Application.routes.draw do
  get "login" => "sessions#new"
  post "login" => "sessions#create", :as => :sessions
  match "logout" => "sessions#destroy", via: [:get, :post]

  resources :shortened_url, :path => "url" do
    collection do
      match "shorten", via: [:get, :post]
    end
  end

  get "/:id" => "shortened_url#follow"
  
  root :to => "application#home"
  

end

app/models/click.rb
class Click < ActiveRecord::Base
  belongs_to :shortened_url, counter_cache: true
end

app/models/shortened_url.rb
require 'digest'

class ShortenedUrl < ActiveRecord::Base
  has_many :clicks

  before_validation :generate_shortcode

  validates_presence_of :url, :message => "can't be blank"
  validates_presence_of :shortcode, :message => "can't be blank"
  validates_format_of :shortcode, :with => /\A[\w\d]+\z/, :message => "is invalid"
  validates_uniqueness_of :shortcode, :message => "must be unique"

  def click!(request)
    self.clicks.create!(:referer => request.referer, :ip => Digest::SHA512.hexdigest(request.remote_ip))
  end

  def generate_shortcode
    while self.shortcode.blank? || ShortenedURL.where("shortcode = ? AND id != ?", self.shortcode.to_s, self.id.to_i).count > 0 
      self.shortcode = (0..6).map{ rand(36).to_s(36) }.join
    end
  end

end

class ShortenedURL < ShortenedUrl
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :check_password, :except => [:home]

  def home
  end
  
  protected
  
  def check_password
    redirect_to login_path unless connected?
  end
  
  def connected?
    session[:password] == ENV["PASSWORD"]
  end
  
  def reset_session
    session[:password] = nil
  end
  
end

app/controllers/sessions_controller.rb
require 'digest'

class SessionsController < ApplicationController
  skip_before_filter :check_password

  def new
    redirect_to shortened_url_index_path if connected?
  end

  def create
    session[:password] = Digest::SHA512.hexdigest(params[:password])
    if connected?
      flash[:notice] = "Okay! C'est toi le boss."
      redirect_to shortened_url_index_path
    else
      render :new
    end
  end
  
  def destroy
    reset_session
    flash[:notice] = "Il est mort !"
    redirect_to login_path
  end
end

app/controllers/shortened_url_controller.rb
class ShortenedUrlController < ApplicationController
  skip_before_filter :check_password, :only => [:follow, :shorten]
  
  # GET /url
  # GET /url.json
  def index
    @urls = ShortenedUrl.order("updated_at ASC").all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @urls }
    end
  end

  # GET /url/1
  # GET /url/1.json
  def show
    @url = ShortenedUrl.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @url }
    end
  end

  # GET /url/new
  # GET /url/new.json
  def new
    @url = ShortenedUrl.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @url }
    end
  end

  # GET /url/1/edit
  def edit
    @url = ShortenedUrl.find(params[:id])
  end

  # POST /url
  # POST /url.json
  def create
    @url = ShortenedUrl.new(surl_params)

    respond_to do |format|
      if @url.save
        format.html { redirect_to @url, :notice => 'Shortened url was successfully created.' }
        format.json { render :json => @url, :status => :created, :location => @url }
      else
        format.html { render :action => "new" }
        format.json { render :json => @url.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /url/1
  # PUT /url/1.json
  def update
    @url = ShortenedUrl.find(params[:id])

    respond_to do |format|
      if @url.update_attributes(surl_params)
        format.html { redirect_to @url, :notice => 'Shortened url was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @url.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /url/1
  # DELETE /url/1.json
  def destroy
    @url = ShortenedUrl.find(params[:id])
    @url.destroy

    respond_to do |format|
      format.html { redirect_to shortened_url_index_url }
      format.json { head :no_content }
    end
  end
    
  def follow
    @url = ShortenedURL.find_by_shortcode(params[:id])
    if @url.nil?
      biturl = Bitly.client.expand("https://pof.pm/#{params[:id]}")
      biturl = Bitly.client.expand("https://bit.ly/#{params[:id]}") if biturl.long_url.blank?
      unless biturl.long_url.nil?
        @url = ShortenedURL.create(:shortcode => params[:id], :url => biturl.long_url, :from_bitly => true, :bitly_clicks => biturl.global_clicks)
      end
    end

    if @url.nil?
      render :nothing => true, :status => 404
    else
      @url.click!(request)
      redirect_to @url.url, :status_code => 302
    end
  end
  
  def shorten
    if params.permit(:token)[:token] == ENV["TOKEN"] && !params[:url].blank?
      @url = ShortenedURL.find_by_url(api_surl_params[:url])
      @url = ShortenedURL.create(api_surl_params) if @url.nil?
      if @url
        respond_to do |format|
          format.json { render :json => { :shortURL => "http://pof.pm/#{@url.shortcode}" } }
          format.text { render :text => "http://pof.pm/#{@url.shortcode}" }
          format.html { render :text => "http://pof.pm/#{@url.shortcode}" }
        end
      else
        render :nothing => true, :status => 400
      end
    else
      render :nothing => true, :status => 400
    end
  end

  private

 def api_surl_params
   params.permit(:shortcode, :url)
  end

 def surl_params
   params.require(:shortened_url).permit(:description, :shortcode, :title, :url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def shortened_urls_path(*args)
    shortened_url_index_path(*args)
  end
  
  def shortened_urls_url(*args)
    shortened_url_index_url(*args)
  end
    
  def title(page_title)
    content_for(:title) { page_title }
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shortened_url_helper.rb
module ShortenedUrlHelper
end

app/views/application/home.html.erb
<%= stylesheet_link_tag    "home", :media => "all" %>
<%= title "Pof Magicfingers / gicma.dev" %>
<div class="container">
  <%= link_to "https://pofmagicfingers.fr/", class: "item" do %>
    <%= image_tag "pofmagicfingers.jpg" %>
    <h2>Pod&shy;casts, Gaming, etc</h2>
  <% end %>
  <%= link_to "https://gicma.dev/", class: "item" do %>
    <%= image_tag "gicma.dev.jpg" %>
    <h2>Déve&shy;lop&shy;pe&shy;ment</h2>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="controller-<%= params[:controller] %> action-<%= params[:action] %>">
<head>
  <title><%= content_for?(:title) ? yield(:title) : 'pof.pm' %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shortened_url/_form.html.erb
<%= form_for(@url) do |f| %>
  <% if @url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@url.errors.count, "error") %> prohibited this shortened_url from being saved:</h2>

      <ul>
      <% @url.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :shortcode %><br />
    <%= f.text_field :shortcode %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shortened_url/edit.html.erb
<h1>Editing shortened_url</h1>

<%= render 'form' %>

<%= link_to 'Show', @url %> |
<%= link_to 'Back', shortened_url_index_path %>

app/views/shortened_url/index.html.erb
<h1>Listing shortened_urls</h1>

<table>
  <tr>
    <th>Shortcode</th>
    <th>Url</th>
    <th>Clicks</th>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @urls.each do |shortened_url| %>
  <tr>
    <td><%= link_to shortened_url.shortcode, "https://pof.pm/#{shortened_url.shortcode}"  %></td>
    <td><%= shortened_url.url.truncate(40) %></td>
    <td>
		<% if shortened_url.bitly_clicks.to_i > 0 %>
			<%= "#{shortened_url.bitly_clicks} + #{shortened_url.clicks.size} (#{shortened_url.bitly_clicks+shortened_url.clicks.size})" %>
		<% else %>
		 	<%= shortened_url.clicks.size %>
		<% end %>
	</td>
    <td><%= shortened_url.title.blank? ? raw("<i>None</i>") : shortened_url.title %></td>
    <td><%= shortened_url.description.blank? ? raw("<i>None</i>") : shortened_url.description %></td>
    <td><%= link_to 'Show', shortened_url %></td>
    <td><%= link_to 'Edit', edit_shortened_url_path(shortened_url) %></td>
    <td><%= link_to 'Destroy', shortened_url, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shortened url', new_shortened_url_path %>

app/views/shortened_url/new.html.erb
<h1>New shortened_url</h1>

<%= render 'form' %>

<%= link_to 'Back', shortened_url_index_path %>

app/views/shortened_url/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @url.title %>
</p>

<p>
  <b>Url:</b>
  <%= @url.url %>
</p>

<p>
  <b>Description:</b>
  <%= @url.description %>
</p>

<p>
  <b>Shortcode:</b>
  <%= @url.shortcode %>
</p>


<%= link_to 'Edit', edit_shortened_url_path(@url) %> |
<%= link_to 'Back', shortened_url_index_path %>